settings:
  legacy:
    force: true
    interval: 100ms
schema:
- name: api.jorgechato.com
  path: .
  commands:
    clean:
      status: true
    fmt:
      status: true
    test:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - mod
    paths:
    - api
    - utils
    - go.mod
    - server.go
    - github
    ignored_paths:
    - .git
    - .realize
    - vendor
    - out
