dist: trusty
sudo: required
language: go
go:
  - 1.10.x
sudo: true
services:
  - docker
env:
  global:
    - IMAGE_NAME=jorgechato/api.jorgechato.com


before_install:
  - docker pull "$IMAGE_NAME" || true

install:
  - make dep
  - make vendor

script:
  - make test || true

after_success:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  target-branch: master
  on:
    branch: master

after_script:
  - docker images
